### PR TITLE
Potential fix for network/config API changes

### PR DESCRIPTION
**Pull request by patridge**
- [x] Add missing namespace for network interfaces
- [x] Return config sample to retrieving config values

### CODE REVIEW

**Comment by jorgedevs** [comment]
@patridge Apologies but forgot all about this PR. If the changes are not in yet, can you update so we can merge it? thanks!

**Comment by patridge** [comment]
I've forgotten about it too. Let me merge it up to date and make sure it is still valid. Those APIs were pretty fluid when I did this PR.

**Comment by patridge** [comment]
Merge conflict is fixed, but I haven't tested this again yet. (I don't even remember what triggered the issue that lead to the PR anymore.)

**Comment by patridge** [comment]
I've realigned the C# and VB WiFi_Basics samples, which had drifted a bit in what they did. That also involved updating C# to use Resolver.Log.* all over.

**Comment by patridge** [comment]
I am getting some `ioctl GetSetConfigurationValue failed OperationNotPermitted` logging when running the Config_Files sample on a Feather board with the latest preview OS and latest local dev repos.

```console
[1/25/2023 09:20:24] Meadow StdOut: =========================OutputMeadowOSInfo============================
[1/25/2023 09:20:24] Meadow StdOut: OS version: 0.9.3.14
[1/25/2023 09:20:24] Meadow StdOut: Mono version: 0.9.3.14
[1/25/2023 09:20:24] Meadow StdOut: Build date: 23 Jan 2023 20:01:01 UTC
[1/25/2023 09:20:24] Meadow StdOut: =======================================================================
[1/25/2023 09:20:24] Meadow StdOut: ====================OutputDeviceConfigurationInfo======================
[1/25/2023 09:20:24] Meadow StdOut: Automatically connect to network: True
[1/25/2023 09:20:24] Meadow StdOut: Get time at startup: True
[1/25/2023 09:20:24] Meadow StdOut: ioctl GetSetConfigurationValue failed OperationNotPermitted
[1/25/2023 09:20:24] Meadow StdOut: Configuration ioctl failed, result code: 1
[1/25/2023 09:20:24] Meadow StdOut: Default access point: False
[1/25/2023 09:20:24] Meadow StdOut: Maximum retry count: 7
[1/25/2023 09:20:24] Meadow StdOut: ioctl GetSetConfigurationValue failed OperationNotPermitted
[1/25/2023 09:20:24] Meadow StdOut: Configuration ioctl failed, result code: 1
[1/25/2023 09:20:24] Meadow StdOut: Maximum retry count: False
[1/25/2023 09:20:24] Meadow StdOut: =======================================================================
```

**Comment by patridge** [comment]
Those `ioctl` errors were issues with my code in how it is retrieving config values. I'll update with my latest changes and the PR should be ready for review again.

**Review by jorgedevs — APPROVED** [review]

**Pull request merged**
